name: publish_documents-with deploy key
on:
  push:
    branches: [ master ]
    tags: ["v*"]
  pull_request:
    branches: [ master ]
    tags: ["v*"]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name : Extract ref name
        run: echo "##[set-output name=ref;]$(echo ${GITHUB_REF##*/})"
        id: extract_ref

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H:%M:%S')"

      - name : Gen dummy page
        run: |
          mkdir -p docs
          cat > docs/index.html <<EOL
          <!doctype html>
          <html>
            <head>
              <title>GitHub Pages deployed!</title>
            </head>
            <body>
              <p>GitHub Pages with <strong>${{ github.sha }}</strong> commit ID has been deployed through <a href="https://github.com/marketplace/actions/github-pages">GitHub Pages action</a> successfully.</p>
              <p>${{ steps.date.outputs.date }}</p>
            </body>
          </html>
          EOL

      #- name: Create Documents
        #run: doxygen doxygen/Doxyfile

      ## This step is required because ssh-agent process spawned from Deploy step never finish
      #- name: Cleanup ssh-agent
        #run: pkill ssh-agent

      - name: Deploy to external git pages
        # Forked version of peaceiris/actions-gh-pages, which fixes the GHES issue
        uses: jiminj/actions-gh-pages@68e93fe5973470f354d8b5d54fad1ab00048c996
        continue-on-error: true
        with:
          allow_empty_commit: true
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: jiminj/actions-test-external
          #github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          destination_dir: deploykey

      - name: Cleanup ssh-agent
        continue-on-error: true
        run: |
          pkill -f 'ssh-agent -a /tmp/ssh-auth.sock'
          rm '/home/actions-runner/.ssh/github'
          rm '/home/actions-runner/.ssh/config'
          rm '/home/actions-runner/.ssh/known_hosts'

      - name: Deploy to external git pages - with host address
        uses: jiminj/actions-gh-pages@68e93fe5973470f354d8b5d54fad1ab00048c996
        continue-on-error: true
        with:
          allow_empty_commit: true
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: github.com/jiminj/actions-test-external
          publish_dir: ./docs
          destination_dir: deploykey-withhost

      - name: Cleanup ssh-agent
        continue-on-error: true
        run: |
          pkill -f 'ssh-agent -a /tmp/ssh-auth.sock'
          rm '/home/actions-runner/.ssh/github'
          rm '/home/actions-runner/.ssh/config'
          rm '/home/actions-runner/.ssh/known_hosts'

      - name: Deploy to external git pages - with ssh proxy
        uses: jiminj/actions-gh-pages@68e93fe5973470f354d8b5d54fad1ab00048c996
        continue-on-error: true
        with:
          allow_empty_commit: true
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          ssh_proxy: ssh_proxy
          external_repository: github.com/jiminj/actions-test-external
          publish_dir: ./docs
          destination_dir: deploykey-sshproxy

      - name: Cleanup ssh-agent
        continue-on-error: true
        run: |
          pkill -f 'ssh-agent -a /tmp/ssh-auth.sock'
          rm '/home/actions-runner/.ssh/github'
          rm '/home/actions-runner/.ssh/config'
          rm '/home/actions-runner/.ssh/known_hosts'

      - name: Deploy to external git pages - with https host address
        uses: jiminj/actions-gh-pages@68e93fe5973470f354d8b5d54fad1ab00048c996
        continue-on-error: true
        with:
          allow_empty_commit: true
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: https://github.com/jiminj/actions-test-external
          publish_dir: ./docs
          destination_dir: deploykey-withhttpshost

      - name: Deploy to external git pages - with personal_token
        uses: jiminj/actions-gh-pages@68e93fe5973470f354d8b5d54fad1ab00048c996
        continue-on-error: true
        with:
          allow_empty_commit: true
          personal_token: ${{ secrets.ACTIONS_PAT }}
          external_repository: jiminj/actions-test-external
          publish_dir: ./docs
          destination_dir: deploykey-pat

      - name: Deploy to external git pages - with personal_token
        uses: jiminj/actions-gh-pages@68e93fe5973470f354d8b5d54fad1ab00048c996
        continue-on-error: true
        with:
          allow_empty_commit: true
          personal_token: ${{ secrets.ACTIONS_PAT }}
          external_repository: github.com/jiminj/actions-test-external
          publish_dir: ./docs
          destination_dir: deploykey-pat-withhost

